package oscmd

import (
	"hercules_compiler/rce-executor/executor"
	"hercules_compiler/rce-executor/modules"
)

func init() {
	modules.AddModule(OSCmdModuleName)
	executor.RegisterCmd(OSCmdModuleName, CmdNameAddGroup, AddGroup)
	executor.RegisterCmd(OSCmdModuleName, CmdNameAddUser, AddUser)
	executor.RegisterCmd(OSCmdModuleName, CmdNameMakeDir, MakeDir)
	executor.RegisterCmd(OSCmdModuleName, CmdNameChangeOwnAndGroup, ChangeOwnAndGroup)
	executor.RegisterCmd(OSCmdModuleName, CmdNameUnzipFile, UnzipFile)
	executor.RegisterCmd(OSCmdModuleName, CmdNameDownloadFile, DownloadFile)
	executor.RegisterCmd(OSCmdModuleName, CmdNameMD5Sum, MD5Sum)
	executor.RegisterCmd(OSCmdModuleName, CmdNameChangeMode, ChangeMode)
	executor.RegisterCmd(OSCmdModuleName, CmdNameMove, Move)
	executor.RegisterCmd(OSCmdModuleName, CmdNameCopy, Copy)
	executor.RegisterCmd(OSCmdModuleName, CmdNameRemove, Remove)
	executor.RegisterCmd(OSCmdModuleName, CmdNameNohup, Nohup)
	executor.RegisterCmd(OSCmdModuleName, CmdNameKillProcessByPID, KillProcessByPID)
	executor.RegisterCmd(OSCmdModuleName, CmdNameProcessStatus, ProcessStatus)
	executor.RegisterCmd(OSCmdModuleName, CmdNameTextToFile, TextToFile)
	executor.RegisterCmd(OSCmdModuleName, CmdNameLsbRelease, LsbRelease)
	executor.RegisterCmd(OSCmdModuleName, CmdNameCat, Cat)
	executor.RegisterCmd(OSCmdModuleName, CmdNameList, List)
	executor.RegisterCmd(OSCmdModuleName, CmdNameSed, Sed)
	executor.RegisterCmd(OSCmdModuleName, CmdNameLinuxDist, LinuxDist)
	executor.RegisterCmd(OSCmdModuleName, CmdNameYumPackageInstall, YumPackageInstall)
	executor.RegisterCmd(OSCmdModuleName, CmdNameDisableFirewall, DisableFireWall)
	executor.RegisterCmd(OSCmdModuleName, CmdNameDisableSelinux, DisableSELinux)
	executor.RegisterCmd(OSCmdModuleName, CmdNamePing, Ping)
	executor.RegisterCmd(OSCmdModuleName, CmdNameDisplayFileSystem, DisplayFileSystem)
	executor.RegisterCmd(OSCmdModuleName, CmdNameGetMemorySize, GetMemorySize)
	executor.RegisterCmd(OSCmdModuleName, CmdNameFind, Find)
	executor.RegisterCmd(OSCmdModuleName, CmdNameDisplayFileSystemByPath, DisplayFileSystemByPath)
	executor.RegisterCmd(OSCmdModuleName, CmdNameGetCurrentRunLevelInit, GetCurRunLevelInit)
	executor.RegisterCmd(OSCmdModuleName, CmdNameSetRunLevelInit, SetRunLevelInit)
	executor.RegisterCmd(OSCmdModuleName, CmdNameIsolateRunLevelInit, IsolateRunLevelInit)
	executor.RegisterCmd(OSCmdModuleName, CmdNameGetCurrentRunLevelSctrl, GetCurRunLevelSctrl)
	executor.RegisterCmd(OSCmdModuleName, CmdNameSetRunLevelSctrl, SetRunLevelSctrl)
	executor.RegisterCmd(OSCmdModuleName, CmdNameIsolateRunLevelSctrl, IsolateRunLevelSctrl)
	executor.RegisterCmd(OSCmdModuleName, CmdNameGetCurrentRunLevel, GetCurRunLevel)
	executor.RegisterCmd(OSCmdModuleName, CmdNameSetRunLevel, SetRunLevel)
	executor.RegisterCmd(OSCmdModuleName, CmdNameIsolateRunLevel, IsolateRunLevel)
	executor.RegisterCmd(OSCmdModuleName, CmdNameSourceFile, SourceFile)
	executor.RegisterCmd(OSCmdModuleName, CmdNameGetGrubFile, GetGrubFile)
	executor.RegisterCmd(OSCmdModuleName, CmdNameReplaceFileText, ReplaceFileText)
	executor.RegisterCmd(OSCmdModuleName, CmdNameLink, Link)
	executor.RegisterCmd(OSCmdModuleName, CmdNameTouch, Touch)
	executor.RegisterCmd(OSCmdModuleName, CmdNameRpmInstall, RpmInstall)
	executor.RegisterCmd(OSCmdModuleName, CmdNameAddSSHAuthorizedKeys, AddSSHAuthorizedKeys)
	executor.RegisterCmd(OSCmdModuleName, CmdNameChangeDir, ChangeDir)
	executor.RegisterCmd(OSCmdModuleName, CmdNameSplitTextGetIndexValue, SplitTextGetIndexValue)
	executor.RegisterCmd(OSCmdModuleName, CmdNameGetCPUInformation, GetCPUInformation)
	executor.RegisterCmd(OSCmdModuleName, CmdNameReadFile, ReadFile)
	executor.RegisterCmd(OSCmdModuleName, CmdNamePsEfInformation, GetPsInfoByPid)
	executor.RegisterCmd(OSCmdModuleName, CmdNameYumRemove, YumRemove)
	executor.RegisterCmd(OSCmdModuleName, CmdNameBackupYumRepos, BackupYumRepos)
	executor.RegisterCmd(OSCmdModuleName, CmdNameYumLocalPackagesInstall, YumLocalPackagesInstall)
	executor.RegisterCmd(OSCmdModuleName, CmdNameDirUseSpace, DirUseSpace)
	executor.RegisterCmd(OSCmdModuleName, CmdNameGrepLine, GrepLine)
	executor.RegisterCmd(OSCmdModuleName, CmdNameDirectoryCanDo, DirectoryCanDo)
	executor.RegisterCmd(OSCmdModuleName, CmdNamePortValid, PortValid)
	executor.RegisterCmd(OSCmdModuleName, CmdNameSysCtl, SysCtl)
	executor.RegisterCmd(OSCmdModuleName, CmdNameTransferFileToTarget, TransferFileToTarget)
	executor.RegisterCmd(OSCmdModuleName, CmdNameSetEnvironmentLang, SetEnvironmentLang)
	executor.RegisterCmd(OSCmdModuleName, CmdNameGrepPidOf, GrepPidOf)
	executor.RegisterCmd(OSCmdModuleName, CmdNameGetPortByPID, GetPortByPID)
	executor.RegisterCmd(OSCmdModuleName, CmdNameGetMysqldPath, GetMysqldPath)
	executor.RegisterCmd(OSCmdModuleName, CmdNameGetMysqlServerID, GetMysqlServerID)
	executor.RegisterCmd(OSCmdModuleName, CmdNameGetSlaveIP, GetSlaveIP)
	executor.RegisterCmd(OSCmdModuleName, CmdNameOSVersionAvailable, OSVersionAvailable)
	executor.RegisterCmd(OSCmdModuleName, CmdAddParamsToConf, AddParamsToConf)
	executor.RegisterCmd(OSCmdModuleName, CmdNameLs, Ls)
	executor.RegisterCmd(OSCmdModuleName, CmdNameTest, Test)
	executor.RegisterCmd(OSCmdModuleName, CmdNameCheckMysqlPort, CheckMysqlPort)
	executor.RegisterCmd(OSCmdModuleName, CmdNameCheckMysqlPortInConf, CheckMysqlPortInConf)
	executor.RegisterCmd(OSCmdModuleName, CmdNameGetAddMGRIp, GetAddMGRIp)
	executor.RegisterCmd(OSCmdModuleName, CmdNameGetMGRWhiteList, GetMGRWhiteList)
	executor.RegisterCmd(OSCmdModuleName, CmdNameUnInstallSoftware, UnInstallSoftware)
	executor.RegisterCmd(OSCmdModuleName, CmdNameSetScriptTaskFailed, SetScriptTaskFailed)
}
